//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.DTO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserDTO
    {
        public UserDTO() {}
    
        public long Id { get; set; }
        public string LoginName { get; set; }
        public string PasswordHash { get; set; }
        public string Salt { get; set; }
        public string Nickname { get; set; }
        public System.DateTime RegDate { get; set; }
        public DateTime Birtdate { get; set; }
        public string Description { get; set; }
        public bool SharedProfile { get; set; }
        public byte[] AvatarContent { get; set; }
        public string AvatarMime { get; set; }

    }
}
